credentials:
  usernames:
    bank123:
      email: abdullahmoosa128@gmail.com
      name: BankAI
      password: $2b$12$mZr87vmHT153l3aaLzeFpukwUjvQx2oW8jSIq5P1JLSg4QCJgzhm2
cookie:
  expiry_days: 0
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - abdullahmoosa128@gmail.com